#pragma once
#include "CUDADefines.h"
#include "HashRandom.h"

#define FIRESTARTER_EVOLVE   1
#define FIRESTARTER_UNIT     2
#define FIRESTARTER_PROCESS  3
#define FIRESTARTER_OPTIMIZE 4
#define FIRESTARTER_SOLUTION 5
#define FIRESTARTER_MODE     FIRESTARTER_PROCESS

#if FIRESTARTER_MODE == FIRESTARTER_EVOLVE
#define PROGRAM_POPULATION 4352
#define PROGRAM_ITERATIONS 512
#define PROGRAM_GENERATIONS 10  // Must be even!
#define PROGRAM_PRECISION 256
#define PROGRAM_UNITS 1
#define PROGRAM_STATES 1
#elif FIRESTARTER_MODE == FIRESTARTER_UNIT
#define PROGRAM_POPULATION 4352 * 8
#define PROGRAM_ITERATIONS 256
#define PROGRAM_GENERATIONS 100 // Must be even!
#define PROGRAM_PRECISION 256
#define PROGRAM_UNITS 1
#define PROGRAM_STATES 4
#elif FIRESTARTER_MODE == FIRESTARTER_PROCESS
#define PROGRAM_POPULATION 4352 * 8
#define PROGRAM_ITERATIONS 256
#define PROGRAM_GENERATIONS 100 // Must be even!
#define PROGRAM_PRECISION 256
#define PROGRAM_UNITS 4
#define PROGRAM_STATES 4
#else
#define PROGRAM_POPULATION 4352 * 16
#define PROGRAM_ITERATIONS 512
#define PROGRAM_GENERATIONS 100 // Must be even!
#define PROGRAM_PRECISION 256
#define PROGRAM_UNITS 1
#define PROGRAM_STATES 1
#endif

#define PROGRAM_INSTRUCTIONS 32
#define PROGRAM_VARIATIONS 3

#define SAMPLE_MIN 0.0f
#define SAMPLE_MAX (2.0f * 3.14159265f)
#define SAMPLE_ITERATIONS 15
#define EVOLUTION_FACTOR 0.1f
#define EVOLUTION_START_FACTOR 4.0f
#define EVOLUTION_SAMPLES 16
#define START_RESULT 10.0f
