#pragma once
#include "CUDADefines.h"
#include "HashRandom.h"

#define FIRESTARTER_INSTRUCTIONS 32
#define FIRESTARTER_VARIATIONS   3

#define FIRESTARTER_EVOLVE   1
#define FIRESTARTER_UNIT     2
#define FIRESTARTER_PROCESS  3
#define FIRESTARTER_OPTIMIZE 4
#define FIRESTARTER_COMPLETE 6
#define FIRESTARTER_SOLUTION 7
#define FIRESTARTER_MODE     FIRESTARTER_OPTIMIZE

#define EVOLVE_UNITS 1
#define EVOLVE_STATES 1
#define EVOLVE_POPULATION 4352
#define EVOLVE_ITERATIONS 512
#define EVOLVE_GENERATIONS 10
#define EVOLVE_PRECISION 256

#define OPTIMIZE_UNITS 1
#define OPTIMIZE_STATES 1
#define OPTIMIZE_POPULATION 4352 * 16
#define OPTIMIZE_ITERATIONS 512
#define OPTIMIZE_GENERATIONS 100
#define OPTIMIZE_PRECISION 256

#define UNIT_UNITS 1
#define UNIT_STATES 4
#define UNIT_POPULATION 4352 * 8
#define UNIT_ITERATIONS 256
#define UNIT_GENERATIONS 100
#define UNIT_PRECISION 256

#define PROCESS_UNITS 4
#define PROCESS_STATES 8
#define PROCESS_POPULATION 4352 * 8
#define PROCESS_ITERATIONS 128
#define PROCESS_GENERATIONS 100
#define PROCESS_PRECISION 256

#define SAMPLE_MIN 0.0f
#define SAMPLE_MAX (2.0f * 3.14159265f)
#define SAMPLE_ITERATIONS 15
#define EVOLUTION_FACTOR 0.1f
#define EVOLUTION_START_FACTOR 4.0f
#define EVOLUTION_SAMPLES 16
#define START_RESULT 10.0f
