#pragma once
#include "CUDADefines.h"
#include "HashRandom.h"

#define FIRESTARTER_EVOLVE   0
#define FIRESTARTER_OPTIMIZE 1
#define FIRESTARTER_SOLUTION 2
#define FIRESTARTER_MODE     FIRESTARTER_EVOLVE

#if FIRESTARTER_MODE == FIRESTARTER_EVOLVE
#define PROGRAM_POPULATION 4352
#define PROGRAM_ITERATIONS 512
#define PROGRAM_GENERATIONS 10  // Must be even!
#define PROGRAM_PRECISION 256
#else
#define PROGRAM_POPULATION 4352 * 4
#define PROGRAM_ITERATIONS 1024 * 4
#define PROGRAM_GENERATIONS 100 // Must be even!
#define PROGRAM_PRECISION 256
#endif

#define PROGRAM_UNITS 1

#define PROGRAM_INSTRUCTIONS 32
#define PROGRAM_VARIATIONS 3

#define SAMPLE_MIN 0.0f
#define SAMPLE_MAX (2.0f * 3.14159265f)
#define SAMPLE_ITERATIONS 15
#define EVOLUTION_FACTOR 0.1f
#define EVOLUTION_START_FACTOR 4.0f
#define EVOLUTION_LUCK 0.1f
#define EVOLUTION_SAMPLES 16
#define START_RESULT 10.0f
